# Automatically generated by configure - do not modify
SRC_PATH=/Users/hackveda/dev_ios_emulate/xnu-qemu-arm64/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
